id = "rainbow-csv"
name = "Rainbow CSV"
version = "0.0.2"
schema_version = 1
authors = ["Hans <weartistt@gmail.com>"]
description = "Highlight CSV with different rainbow colors to make them more readable"
repository = "https://github.com/weartist/zed-rainbow-csv"

[grammars.csv]
repository = "https://github.com/weartist/rainbow-csv-tree-sitter"
commit = "896e6d09b23a1b0d87e45bf97ca34a249f41495c"

[grammars.tsv]
repository = "https://github.com/weartist/rainbow-tsv-tree-sitter"
commit = "fdbd83fc30690777822b7ab183f57664c11310e9"
